command_prefix              : '\+'
log_level                   : 'log'

mud:
    host                    : 'localhost'
    port                    : 2067
    user                    : 'NodeBot'
    pass                    : '!'

plugins                     : [finger]

output:
    header                  : '[center(< %s >, 78, =)]'
    mid                     : '[repeat(-,78)]'
    prefix                  : '\[%s\]'
    tail                    : '[repeat(=, 78)]'