command_prefix              : '\+'
log_level                   : 'log'

mud:
    hostname                : 'localhost'
    port                    : 2067
    username                : 'NodeBot'
    password                : '!'

database:
    adapter                 : 'SQLite'

plugins                     : [Finger]

output:
    header                  : '[center(< %s >, 78, =)]'
    mid                     : '[repeat(-,78)]'
    prefix                  : '\[%s\]'
    tail                    : '[repeat(=, 78)]'