plugins                     : [Jobs]

log_level                   : 'log'

contexts:
  Mud:
    client:
      hostname              : 'localhost'
      port                  : 2067
      username              : 'NodeBot'
      password              : '!'
    input:
      prefix                : '\+'
    output:
      header                : '[center(< %s >, 78, =)]'
      mid                   : '[repeat(-,78)]'
      prefix                : '\[%s\]'
      tail                  : '[repeat(=, 78)]'