plugins:
  - Dice
  - Meetme

log_level                   : debug

contexts:
  Mud:
    client:
      name                  : 'TableMUSH'
      hostname              : 'mud.tablemush.org'
      port                  : 4201
      username              : 'NodeBot'
      password              : '!'
      type                  : mush
    input:
      prefix                : '\+'
    output:
      header                : '[center(< %s >, 78, =)]'
      mid                   : '[repeat(-,78)]'
      prefix                : '%ch%cx\[%cg%s%cx\]%cn'
      tail                  : '[repeat(=, 78)]'
