command_prefix              : '\+'

database:
    adapter                 : 'SQLite'

log_level                   : 'log'

mud:
    hostname                : 'localhost'
    port                    : 2067
    username                : 'NodeBot'
    password                : '!'

output:
    header                  : '[center(< %s >, 78, =)]'
    mid                     : '[repeat(-,78)]'
    prefix                  : '\[%s\]'
    tail                    : '[repeat(=, 78)]'

plugins                     : [Jobs]
