plugins:
  Dice:
    default_parser          : dd
  Meetme:

log_level                   : debug

contexts:
  Mud:
    client:
      name                  : SampleMUSH
      hostname              : samplemush.org
      port                  : 4202
      username              : NodeBot
      password              : !
      type                  : mush
    input:
      prefix                : \+
    output:
      header                : '[center(< %s >, 78, =)]'
      mid                   : '[repeat(-,78)]'
      prefix                : '%ch%cx\[%cg%s%cx\]%cn'
      tail                  : '[repeat(=, 78)]'